import { Link } from 'react-router-dom'
import styles from './LegalPage.module.css'

const EFFECTIVE_DATE = '17 June 2026'
const CONTACT_EMAIL = 'legal@myopenpantry.com'
const SERVICE_NAME = 'Pantry'
const SITE_URL = 'myopenpantry.com'

export default function PrivacyPage() {
  return (
    <div className={styles.page}>
      <main className="wide-col">
        <div className={styles.hero}>
          <Link to="/" className={styles.brand}>{SERVICE_NAME}</Link>
          <h1 className={styles.title}>Privacy Policy</h1>
          <p className={styles.updated}>Effective date: {EFFECTIVE_DATE}</p>
        </div>

        <div className={styles.body}>
          <div className={styles.notice}>
            This Privacy Policy explains how {SERVICE_NAME} collects, uses, and protects your personal information when you use our service at {SITE_URL}. We are committed to handling your data responsibly and in compliance with applicable data protection law, including the UK General Data Protection Regulation (UK GDPR) and the Data Protection Act 2018.
          </div>

          <h2>1. Who We Are</h2>
          <p>
            {SERVICE_NAME} ("{SERVICE_NAME}", "we", "us", "our") operates the recipe management platform at {SITE_URL}. We are the data controller for the personal information described in this policy. If you have any questions or wish to exercise your rights, please contact us at <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.
          </p>

          <h2>2. Information We Collect</h2>

          <h3>2.1 Information you provide directly</h3>
          <ul>
            <li><strong>Account information:</strong> your email address, display name, and password when you register.</li>
            <li><strong>Profile information:</strong> optional details you add to your profile, including your country, gender, and age bracket.</li>
            <li><strong>Recipe content:</strong> recipes, ingredients, steps, photos, and tags you add to your collection.</li>
            <li><strong>User interactions:</strong> ratings and favourites you give to other users' recipes.</li>
            <li><strong>Communications:</strong> messages you send us, including support enquiries.</li>
          </ul>

          <h3>2.2 Information generated by your use of the service</h3>
          <ul>
            <li><strong>Usage data:</strong> which features you use, pages you visit, searches you perform, and actions you take within the service.</li>
            <li><strong>Device and connection data:</strong> IP address, browser type, operating system, and referring URLs, collected automatically via Cloudflare infrastructure.</li>
            <li><strong>Session data:</strong> authentication session tokens stored in your browser's local storage to keep you signed in.</li>
          </ul>

          <h3>2.3 Content you submit for AI processing</h3>
          <p>
            When you use our AI extraction features, the content you submit — including screenshot images and webpage URLs — is transmitted to our AI processing provider (Anthropic) to extract recipe data. This content is processed to generate recipe output and is not used to train AI models under our agreements with Anthropic.
          </p>

          <h2>3. How We Use Your Information</h2>
          <p>We use your information to:</p>
          <ul>
            <li>Create and manage your account and authenticate your identity.</li>
            <li>Provide the core service: storing and displaying your recipes, enabling search and filtering, and processing AI extraction requests.</li>
            <li>Enable community features: displaying your public profile and recipes to other users where you have enabled this, showing leaderboards, enabling favouriting and ratings.</li>
            <li>Enforce our Terms of Service and protect the safety and integrity of the service, including applying usage limits and detecting abuse.</li>
            <li>Communicate with you about your account, including sending password reset and account security emails.</li>
            <li>Improve the service: analysing aggregated usage patterns to understand how features are used and to prioritise development. We do not build individual profiles for advertising purposes.</li>
            <li>Comply with legal obligations.</li>
          </ul>

          <h2>4. Legal Basis for Processing (UK/EU GDPR)</h2>
          <p>We rely on the following legal bases:</p>
          <ul>
            <li><strong>Contract:</strong> Processing necessary to provide the service you have signed up for — account creation, recipe storage, AI extraction, and community features.</li>
            <li><strong>Legitimate interests:</strong> Detecting and preventing abuse, applying rate limits, improving the service through aggregated analytics, and enforcing our Terms. We have assessed these interests as proportionate and not overriding your rights.</li>
            <li><strong>Consent:</strong> Where we ask for your consent to optional data uses, such as optional profile fields (gender, age bracket). You can withdraw consent at any time by removing this information from your profile.</li>
            <li><strong>Legal obligation:</strong> Where we are required by law to retain or disclose information.</li>
          </ul>

          <h2>5. Sharing Your Information</h2>
          <p>We do not sell your personal information. We share it only in the following circumstances:</p>

          <h3>5.1 Service providers</h3>
          <ul>
            <li><strong>Cloudflare:</strong> Our hosting, database (D1), object storage (R2), and CDN provider. All data is processed within Cloudflare's infrastructure. Cloudflare is a processor bound by data processing agreements.</li>
            <li><strong>Anthropic:</strong> Our AI provider for recipe extraction. Content submitted for extraction is sent to Anthropic's API. Anthropic does not use API inputs to train models and is bound by data processing agreements.</li>
          </ul>

          <h3>5.2 Other users</h3>
          <p>
            If you make your profile public, your display name, public recipes, ratings, and any profile information you have provided (country, avatar) will be visible to other {SERVICE_NAME} users. You control your public status from your Profile settings. Private accounts are not visible to other users.
          </p>

          <h3>5.3 Legal requirements</h3>
          <p>
            We may disclose your information where required to do so by law, court order, or regulatory authority, or where we believe disclosure is necessary to protect our rights, your safety, or the safety of others.
          </p>

          <h3>5.4 Business transfers</h3>
          <p>
            If {SERVICE_NAME} is involved in a merger, acquisition, or sale of all or a portion of its assets, your information may be transferred as part of that transaction. We will notify you before your personal information becomes subject to a different privacy policy.
          </p>

          <h2>6. International Data Transfers</h2>
          <p>
            {SERVICE_NAME} uses Cloudflare and Anthropic, which may process data in the United States and other countries outside the UK/EEA. Where we transfer personal data internationally, we ensure appropriate safeguards are in place, including standard contractual clauses or equivalent mechanisms approved by the UK Information Commissioner's Office (ICO).
          </p>

          <h2>7. Data Retention</h2>
          <ul>
            <li><strong>Account and recipe data:</strong> Retained for as long as your account is active. When you delete your account, your personal data is permanently removed from our active systems within 30 days. Anonymised, aggregated data (e.g. usage statistics) may be retained indefinitely.</li>
            <li><strong>Authentication logs and rate limit records:</strong> Retained for up to 90 days for security purposes.</li>
            <li><strong>Backups:</strong> Encrypted backups may retain copies of your data for up to 90 days after deletion before they are overwritten.</li>
            <li><strong>Legal holds:</strong> We may retain specific data for longer periods where required by law or for the establishment, exercise, or defence of legal claims.</li>
          </ul>

          <h2>8. Your Rights</h2>
          <p>
            Under UK GDPR (and, where applicable, EU GDPR), you have the following rights regarding your personal data:
          </p>
          <ul>
            <li><strong>Access:</strong> Request a copy of the personal data we hold about you.</li>
            <li><strong>Rectification:</strong> Ask us to correct inaccurate or incomplete data.</li>
            <li><strong>Erasure:</strong> Ask us to delete your personal data ("right to be forgotten"), subject to legal retention obligations.</li>
            <li><strong>Restriction:</strong> Ask us to restrict processing of your data in certain circumstances.</li>
            <li><strong>Portability:</strong> Request your data in a structured, commonly used, machine-readable format.</li>
            <li><strong>Objection:</strong> Object to processing based on legitimate interests.</li>
            <li><strong>Withdraw consent:</strong> Where processing is based on consent, withdraw it at any time without affecting the lawfulness of prior processing.</li>
          </ul>
          <p>
            To exercise any of these rights, email us at <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>. We will respond within 30 days. You also have the right to lodge a complaint with the UK Information Commissioner's Office (ICO) at <a href="https://ico.org.uk" target="_blank" rel="noopener noreferrer">ico.org.uk</a>.
          </p>
          <p>
            Many rights can be exercised directly within the app: you can edit your profile at any time, export your data, and delete your account from your Profile settings page.
          </p>

          <h2>9. Cookies and Local Storage</h2>
          <p>
            {SERVICE_NAME} uses browser local storage (not cookies) to store your session token and user preferences such as onboarding completion status and notification dismissals. This data is essential for the service to function and does not require your consent under the UK Privacy and Electronic Communications Regulations.
          </p>
          <p>
            We do not use advertising cookies, third-party tracking cookies, or analytics cookies that track you across other sites. Cloudflare may set security-related cookies as part of its DDoS protection and infrastructure services.
          </p>

          <h2>10. Security</h2>
          <p>
            We take the security of your personal data seriously. We implement appropriate technical and organisational measures including:
          </p>
          <ul>
            <li>Passwords stored using bcrypt hashing — we never store plaintext passwords.</li>
            <li>All data in transit encrypted via HTTPS/TLS.</li>
            <li>Data at rest encrypted by Cloudflare's infrastructure.</li>
            <li>Session tokens validated server-side on every authenticated request.</li>
            <li>Rate limiting on authentication endpoints to prevent brute-force attacks.</li>
          </ul>
          <p>
            No method of transmission over the internet or electronic storage is 100% secure. While we strive to protect your information, we cannot guarantee absolute security. In the event of a data breach affecting your rights and freedoms, we will notify the relevant supervisory authority within 72 hours and affected users without undue delay.
          </p>

          <h2>11. Children's Privacy</h2>
          <p>
            {SERVICE_NAME} is not directed at children under 13. We do not knowingly collect personal information from anyone under 13. If we become aware that we have collected personal data from a child under 13, we will delete it immediately. If you believe a child under 13 has provided us with personal information, please contact us at <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.
          </p>

          <h2>12. Changes to This Policy</h2>
          <p>
            We may update this Privacy Policy from time to time. When we do, we will update the effective date at the top of this page. For material changes that affect your rights, we will provide prominent notice within the app or by email. Your continued use of the service after any changes constitutes acceptance of the updated policy.
          </p>

          <h2>13. Contact Us</h2>
          <p>
            If you have questions, concerns, or requests regarding your privacy or this policy, please contact us at:
          </p>
          <p>
            <strong>{SERVICE_NAME}</strong><br />
            Email: <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a><br />
            Website: {SITE_URL}
          </p>

          <div className={styles.footer}>
            <Link to="/terms" className={styles.footerLink}>Terms of Service</Link>
            <Link to="/" className={styles.footerLink}>← Back to Pantry</Link>
          </div>
        </div>
      </main>
    </div>
  )
}
